#!/bin/sh
echo "%%% This file is generated by Makefile." > vc.tex
echo "%%% Do not edit this file!" >> vc.tex
echo "%%%" >> vc.tex
git log -1 --format="format:\\gdef\\GITAbrHash{%h}\\gdef\\GITAuthorDate{%ad}\\gdef\\GITAuthorName{%an}" >> vc.tex